import RoastPages from "@/components/roast-page";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Roaast Me by Prince Elorm",
  description:
    "Get hilariously roasted by AI! Upload your photo and receive witty, harmless roasts generated by artificial intelligence. Fun entertainment app by Prince Elorm.",

  keywords: [
    "AI roast generator",
    "funny roasts",
    "entertainment app",
    "photo roast",
    "AI comedy",
    "Prince Elorm",
    "roast app",
    "humor generator",
    "funny AI",
    "comedy app",
  ],

  openGraph: {
    title: "Roaast Me by Prince Elorm",
    description:
      "Get hilariously roasted by AI! Upload your photo and receive witty, harmless roasts generated by artificial intelligence.",
    url: "https://elorm.xyz/roaastme",
    images: [
      {
        url: "/api/og?title=Roaast Me by Prince Elorm&description=AI-Powered Roast Generator&type=default",
        width: 1200,
        height: 630,
        alt: "Roaast Me by Prince Elorm - AI Roast Generator",
      },
    ],
  },

  twitter: {
    card: "summary_large_image",
    title: "Roaast Me by Prince Elorm",
    description:
      "Get hilariously roasted by AI! Upload your photo and receive witty, harmless roasts generated by artificial intelligence.",
    creator: "@elorm_elom",
    site: "@elorm_elom",
    images: [
      "/api/og?title=Roaast Me by Prince Elorm&description=AI-Powered Roast Generator&type=default",
    ],
  },
};

function RoastPage() {
  return (
    <div className="flex flex-col min-h-screen mt-5 px-6 md:p-10 lg:px-40 md:px-32 md:mx-10 lg:mx-40">
      <RoastPages />
    </div>
  );
}

export default RoastPage;
